name: 'GitHub Actions Bot'

on:
    push:
        branches:
            - dev

jobs:
        auto_deploy:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v2
          - name: 'Get fossil'
            run:  bash ./git.sh
            shell: bash

