name: 'AsmBB Mirror'

on:
    push:
        branches:
            - dev
    schedule:
        - cron:  '0 9 * * *'
jobs:
    test:
        name: GET ASMBB
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2.3.3
          - uses: actions/checkout@master
          - name: 'INSTALL FOSSIL'
            run: |
              # wget -c https://www.fossil-scm.org/fossil/uv/fossil-linux-x64-2.13.tar.gz 1> wget.log
              # tar zxvf fossil-linux-x64-2.13.tar.gz > tar.log
              # chmod a+x ./fossil
              # sudo apt install fossil
              # mkdir asmbb
              # fossil help clone
              # fossil clone https://asm32.info/fossil/repo/asmbb asmbb.fossil
              # cd asmbb
              # fossil open https://asm32.info/fossil/repo/asmbb --repodir ./asmbb
              # cd asmbb
              # ls -l
              # bash ./git.sh
              wget -c https://github.com/baddate/AsmBB-Mirror/raw/master/git.sh -O auto.sh
              echo `pwd`
              chmod a+x ./auto.sh
              bash ./auto.sh
            shell: bash
          - uses: fregante/setup-git-token@v1
              with:
                token: ${{ secrets.TOKEN }}
          - run: git checkout dev
          - run: git push origin dev
