name: 'GitHub Actions Bot'

on:
    push:
        branches:
            - dev

jobs:
    test:
        name: GET ASMBB
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2.3.3
          - name: 'INSTALL FOSSIL'
            run: |
              # wget -c https://www.fossil-scm.org/fossil/uv/fossil-linux-x64-2.13.tar.gz 1> wget.log
              # tar zxvf fossil-linux-x64-2.13.tar.gz > tar.log
              # chmod a+x ./fossil
              # sudo apt install fossil
              # mkdir asmbb
              # fossil help clone
              # fossil clone https://asm32.info/fossil/repo/asmbb asmbb.fossil
              # cd asmbb
              # fossil open https://asm32.info/fossil/repo/asmbb --repodir ./asmbb
              # cd asmbb
              # ls -l
              bash ./git.sh
            shell: bash
