name: 'GitHub Actions Bot'

on:
    push:
        branches:
            - dev

jobs:
    test:
        name: GET ASMBB
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2.3.3
          - name: 'INSTALL FOSSIL'
            run: |
                bash ./git.sh
            shell: bash
