name: 'GitHub Actions Bot'

on:
    push:
        branches:
            - dev

jobs:
       Todo_bot:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v2
            run: |
            git config --global user.email "badgatex@outlook.com"
            git config --global user.name "baddate"
            echo "hi" > test.md
            git add .
            git commit --message 'test actions'
            git push
          # - name: 'Get fossil'
          #   run:  sudo wget -c https://www.fossil-scm.org/index.html/uv/fossil-linux-x64-2.11.1.tar.gz
          # - name: 'Extract fossil'
          #   run:  sudo tar zxvf fossil-linux-x64-2.11.1.tar.gz
          # - name: 'Get AsmBB'
          #   run:  ./fossil clone https://asm32.info/fossil/repo/asmbb asmbb.fossil
          # - name: Actions
          #   run: |
          #         mkdir asmbb
          #         cd asmbb
          # - name: 'Open AsmBB repo'
          #   uses: ./fossil open asmbb.fossil
          # - name: git Actions
          #   run: |
          #         git add .
          #         git commit -m "update"
          #         git push origin master
