name: 'GitHub Actions Bot'

on:
    push:
        branches:
            - dev

jobs:
    test:
        name: Setup
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2.3.3
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
          - name: 'COPY'
            run:  bash ./git.sh
            shell: bash

